export const GET_FOOTER_LIST = 'GET_FOOTER_LIST'

export const GET_NAV_LIST = 'GET_NAV_LIST'

export const GET_BANNER_LIST = 'GET_BANNER_LIST'

export const GET_PERSONAILZED_LIST = 'GET_PERSONAILZED_LIST'

export const GET_PERSONAILZEDMV_LIST = 'GET_PERSONAILZEDMV_LIST'

export const GET_PERSONAILZEDMUSIC_LIST = 'GET_PERSONAILZEDMUSIC_LIST'

export const GET_PLAYDETAIL_LIST = 'GET_PLAYDETAIL_LIST'
